import unittest

from main import part_1, part_2

EXAMPLE = """\
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""

EXAMPLE2 = """\
..S..
..^..
.^.^.
.....
"""


class Day01Test(unittest.TestCase):
    def test_part1_example(self):
        self.assertEqual(21, part_1(EXAMPLE))

    def test_part2_example(self):
        self.assertEqual(40, part_2(EXAMPLE))

    def test_part2_example2(self):
        self.assertEqual(4, part_2(EXAMPLE2))
